### ISSUE TITLE
Problem with OpenBabel while trying to install Avogadro

### ISSUE THREAD

**Issue by cryos** [cryos/avogadro#335]
Hi !

I'm working on Pardus 2008.2 and I have installed the latest version of OpenBabel (2.2.1) in order to compile and install Avogadro 0.9.3. Unfortunately, when I use the make command for Avogadro, I obtain the following lines :

portable build # make  
[  0%] Building CXX object libavogadro/src/CMakeFiles/avogadro-lib.dir/primitiveitemmodel.cpp.o
/home/sebastien/Sources/avogadro-0.9.3/libavogadro/src/primitiveitemmodel.cpp:35:27: error: openbabel/mol.h: No such file or directory  
/home/sebastien/Sources/avogadro-0.9.3/libavogadro/src/primitiveitemmodel.cpp: In member function 'virtual QVariant Avogadro::PrimitiveItemModel::data(const QModelIndex&, int)const':
/home/sebastien/Sources/avogadro-0.9.3/libavogadro/src/primitiveitemmodel.cpp:266: error: 'etab' is not a member of 'OpenBabel'

**\* 2 errors, 0 warnings
make[2]: **\* [libavogadro/src/CMakeFiles/avogadro-lib.dir/primitiveitemmodel.cpp.o] Erreur 1
make[1]: **\* [libavogadro/src/CMakeFiles/avogadro-lib.dir/all] Erreur 2
make: **\* [all] Erreur 2

Reported by: linuxcomics
