### ISSUE TITLE
0.6.0 doesn't build with openbabel 2.2.0b4 on linux

### ISSUE THREAD

**Issue by cryos** [cryos/avogadro#176]
Hi

I'm always attracted by the fancy screenshots of avogadro I see posted on kde planet, but I've never been able to compile it so far as to get it to work, same with this version :-(

I think it would be good for wider testing if the developers show a little restraint regarding the use of the most fancy latest beta version of dependencies!

For completeness, I'm using kubuntu gutsy (7.10) and I compiled openbabel 2.2.0b4 snapshot (after some searching, the only 2.2 available for linux). I got lots of warnings about QFloats, but it stopped on this error:

Linking CXX executable avogadro
/home/simon/src/avogadro-0.6.0/build/libavogadro/src/libavogadro.so: undefined reference to `OpenBabel::OBResidue::GetNumString()'
/home/simon/src/avogadro-0.6.0/build/libavogadro/src/libavogadro.so: undefined reference to`OpenBabel::OBAtom::GetResidue(bool)'
collect2: ld returned 1 exit status
make[2]: **\* [avogadro/src/avogadro] Error 1
make[1]: **\* [avogadro/src/CMakeFiles/avogadro-app.dir/all] Error 2
make: **\* [all] Error 2

Cheers

Simon

Reported by: pooh22
